name: Build
on:
  push:
    branches: master
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  build:
    name: Build on dotnet using ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build project
        run: dotnet build -c Release
      - name: Test project
        run: dotnet test
  publish:
    name: Build Release Package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Repo
        uses: actions/checkout@v2
        
      - name: Get Target Raylib Version
          id: get-tag
        uses: QwerMike/xpath-action@v1
        with:
          filename: "app.config"
          expression: "//appSettings/add[@key='raylib-release-tag']/@value"

      - name: Download raylib Release
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "raysan5/raylib"
          tag: steps.get-tag.outputs.results
          fileName: "*"
      - name: output directory
         run: "ls -la ."

